/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface Schema {
  /**
   * sam with a name
   */
  name: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * Specifies if the template will be in the ts file.
   */
  inlineTemplate?: boolean;
  /**
   * Specifies the type of the thing
   */
  page: string;
  /**
   * path to create the enum
   */
  path?: string;
  /**
   * Specifies if a spec file is generated
   */
  spec?: boolean;
  /**
   * Specifies if it is smart or dumb component
   */
  isSmart?: boolean;
  /**
   * The selector to use for the component.
   */
  selector?: string;
  [k: string]: any;
}
